# Correlation Heatmaps

## Correlation Scores
```{r echo=FALSE, warning=FALSE, message=FALSE, error=FALSE}
library(tidyverse)
library(corrplot)
library(Hmisc)
chlor<-read_csv("data/ChlorinatedCmpds_HouseDust.csv")

chlor.matrix <- as.matrix(chlor[,2:40])
rownames(chlor.matrix) <- chlor$Final_Formula_Match
chlor.cormatrix<-rcorr(chlor.matrix)
chlormatrix<-as.tibble(chlor.cormatrix$r)
print(chlormatrix)

```

## Heatmap
```{r echo=FALSE, warning=FALSE, message=FALSE, error=FALSE}
library(tidyverse)
library(corrplot)
library(Hmisc)
chlor<-read_csv("data/ChlorinatedCmpds_HouseDust.csv")

chlor.matrix <- as.matrix(chlor[,2:40])
rownames(chlor.matrix) <- chlor$Final_Formula_Match
#melt_chlor<-melt(chlor.matrix)
#cast_chlor<-acast(melt_chlor, Var2~Var1)
#chlor.cormatrix<-rcorr(cast_chlor)
chlor.cormatrix<-rcorr(chlor.matrix)
colour1 <- colorRampPalette(c("red","white","blue"))
par(xpd=TRUE)
corrplot(
  chlor.cormatrix$r, 
  order = "hclust",
  hclust.method = "complete",
  )
```

## Heatmap with Dendrogram 


``` {r, eval=FALSE, include=FALSE, warning=FALSE, message=FALSE, error=FALSE}
library(ggplot2)
library(tidyr)
library(ggdendro)
library(reshape2)
library(grid)
library(corrplot)
library(Hmisc)

chlor<-read.csv("C:/Users/Steven Desktop/Documents/MSc2/TargetDecoy/analysis/dust analysis/ChlorAll.csv", header=TRUE)

# Scale data
chlor.scaled <- chlor[,c(1:27,43,46:48)]
chlor.scaled[, c(3:26)] <- scale(chlor.scaled[, 3:26])

# Run clustering
chlor.matrix <- as.matrix(chlor.scaled[, c(3:26)])
rownames(chlor.matrix) <- chlor.scaled$CpdID
chlor.dendro <- as.dendrogram(hclust(d = dist(x = chlor.matrix)))

# Create dendrogram
dendro.plot <- ggdendrogram(data = chlor.dendro, rotate = TRUE)+
            theme(axis.text.x = element_blank())

# Data reordering♣
chlor.long <- gather(data = chlor.scaled, key = Sample, value = Intensity, -c(1:2), -c(27:33))
# Extract the order of the tips in the dendrogram
chlor.order <- order.dendrogram(chlor.dendro)
# Order the levels according to their position in the cluster
chlor.long$CpdID <- factor(x = chlor.long$CpdID,
                               levels = chlor.scaled$CpdID[chlor.order], 
                               ordered = TRUE)

## Heatmap
heatmap.plot <- ggplot(data=chlor.long, mapping=aes(x=Sample, y=CpdID, fill=Intensity)) +
      geom_raster()+
      xlab(label="Sample")+
      scale_fill_gradient(name="Intensity", low="yellow", high="blue")+
      theme(axis.text.y = element_blank(),
        axis.title.y = element_blank(),
        axis.ticks.y = element_blank(),
        legend.position = "top")

##All together
#grid.newpage()
#print(heatmap.plot, vp = viewport(x = 0.4, y = 0.5, width = 0.8, height = 1.0))
#print(dendro.plot, vp = viewport(x = 0.90, y = 0.455, width = 0.2, height = 0.91))

##Alternate (much faster) option for plotting correlation score heatmap
chlor.scaled <- chlor[,c(1:27,43,46:48)]
chlor.scaled[, c(3:26)] <- scale(chlor.scaled[, 3:26])
```

## Heatmap, But Pretty
```{r echo=FALSE, warning=FALSE, message=FALSE, error=FALSE}
library(tidyverse)
library(corrplot)
library(Hmisc)
chlor<-read_csv("data/ChlorinatedCmpds_HouseDust.csv")

chlor.matrix <- as.matrix(chlor[,2:40])
rownames(chlor.matrix) <- chlor$Final_Formula_Match
#melt_chlor<-melt(chlor.matrix)
#cast_chlor<-acast(melt_chlor, Var2~Var1)
#chlor.cormatrix<-rcorr(cast_chlor)
chlor.cormatrix<-rcorr(chlor.matrix)
colour1 <- colorRampPalette(c("red","white","blue"))
par(xpd=TRUE)
corrplot(
  chlor.cormatrix$r, 
  method = "square", 
  type = "full", 
  order = "hclust",
  hclust.method = "complete",
  col = colour1(200), 
  tl.col = "black", 
  tl.srt = 90, 
  tl.cex = 0.5,
  tl.pos = "tl",
  cl.cex = 1.7, #Font size of color index labels
  cl.ratio = 0.25, #Width of color index + labels
  p.mat = chlor.cormatrix$P, 
  sig.level = 0.05, 
  insig = "blank", 
  addrect = 10, #Number of square groupings to outline 
  mar = c(1,1,1,1) #Outer graph margins
  )
```